package com.isuwang.soa.hello.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class Hello{
        
            /**
            *
            **/
            public String name ;
            public String getName(){ return this.name; }
            public void setName(String name){ this.name = name; }

            public String name(){ return this.name; }
            public Hello name(String name){ this.name = name; return this; }
          
            /**
            *
            **/
            public Optional<String> message = Optional.empty();
            public Optional<String> getMessage(){ return this.message; }
            public void setMessage(Optional<String> message){ this.message = message; }

            public Optional<String> message(){ return this.message; }
            public Hello message(Optional<String> message){ this.message = message; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("name").append("\":\"").append(this.name).append("\",");
    stringBuilder.append("\"").append("message").append("\":\"").append(this.message.isPresent()?this.message.get():null).append("\",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      