
        package com.isuwang.soa.hello.scala.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

 Hello Service

        **/
        @Service(name ="com.isuwang.soa.hello.service.HelloService" , version = "1.0.0")
        @Processor(className = "com.isuwang.soa.hello.scala.HelloServiceCodec\$Processor")
        trait HelloService {
        
            /**
            * 
            **/
            
            @throws[com.isuwang.dapeng.core.SoaException]
            def sayHello(
            hello: com.isuwang.soa.hello.scala.domain.Hello ): String

          
            /**
            * 
            **/
            
            @throws[com.isuwang.dapeng.core.SoaException]
            def test(
            content: String ): Unit

          
        }
        