package com.isuwang.soa.hello.scala.domain

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        case class Hello(

         /**
        *
        **/
        
        name : String, /**
        *
        **/
        
        message : Option[String] = None
        )
      